name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger the pipeline when code is pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the job on the latest version of Ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up JDK 17
        uses: actions/setup-java@v2  # Set up JDK 17 using the AdoptOpenJDK distribution
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn clean install  # Build the Spring Boot app using Maven

      - name: Build Docker image
        run: |
          docker build -t yasirmanzoor/capstone-app .  # Build Docker image
          docker push yasirmanzoor/capstone-app  # Push Docker image to Docker Hub
